In [1]:
import gym
import numpy as np
import tensorflow as tf
from bandits_dqn import MetaBanditEnv
from baselines import deepq

In [2]:
env = gym.make("MountainCar-v0")

[2018-06-21 00:48:47,248] Making new env: MountainCar-v0


In [3]:
n_arm = 2
max_obs = 25
cost = 0.001
env2 = MetaBanditEnv(n_arm, max_obs, cost)

In [4]:
env.observation_space

Box(2,)

In [5]:
env2.observation_space

Box(4,)

In [6]:
env.action_space

Discrete(3)

In [7]:
env2.action_space

Discrete(3)

In [8]:
env.reset()

array([-0.44386457,  0.        ])

In [9]:
env2.reset()

array([1, 1, 1, 1])

In [10]:
env2.step(2)

(array([-1, -1, -1, -1]), 0.5, True, {})

In [11]:
env2.term_state

((-1, -1), (-1, -1))

In [12]:
env2._state

((-1, -1), (-1, -1))

In [13]:
init = ((1, 1),) * 4

In [14]:
s = list(init)
arm = 2
p = 1/2
a, b = s[arm]
if np.random.rand() < p:
    s[arm] = (a + 1, b)
else:
    s[arm] = (a, b + 1)
bobit = tuple(s)

In [15]:
np.ravel(bobit)

array([1, 1, 1, 1, 1, 2, 1, 1])

In [16]:
# Required for DQN
env.reset()
new_obs, rew, done, _ = env.step(1)
o = env.observation_space
a = env.action_space.n

In [17]:
print(new_obs,rew,done,_,o,a)

[ -5.08461621e-01  -1.14346349e-04] -1.0 False {} Box(2,) 3


In [119]:
env.action_space

Discrete(3)

In [131]:
env2.reset()

array([1, 1, 1, 1])

In [132]:
env2._state

((1, 1), (1, 1))

In [133]:
env2.step(1)

(array([1, 1, 1, 2]), -0.001, False, {})

In [158]:
env2.step(0)

(array([-1, -1, -1, -1]), 0, True, {})

In [159]:
import multiprocessing

multiprocessing.cpu_count()

4