In [6]:
import gym
import numpy as np
import tensorflow as tf
from bandits_dqn import MetaBanditEnv
from baselines import deepq

In [7]:
env = gym.make("MountainCar-v0")

[2018-06-10 00:40:57,442] Making new env: MountainCar-v0


In [8]:
n_arm = 2
max_obs = 25
cost = 0.001
env2 = MetaBanditEnv(n_arm, max_obs, cost)

In [9]:
env.observation_space

Box(2,)

In [10]:
env2.observation_space

Box(4,)

In [11]:
env.action_space

Discrete(3)

In [12]:
env2.action_space

Discrete(3)

In [13]:
env.reset()

array([-0.46605272,  0.        ])

In [14]:
env2.reset()

array([1, 1, 1, 1])

In [15]:
env2.step(2)

(array([-1., -1., -1., -1.]), 0.5, True, {})

In [16]:
env2.term_state

array([-1., -1., -1., -1.])

In [17]:
env2._state

((1, 1), (1, 1))

In [46]:
init = ((1, 1),) * 4

In [23]:
s = list(init)
arm = 2
p = 1/2
a, b = s[arm]
if np.random.rand() < p:
    s[arm] = (a + 1, b)
else:
    s[arm] = (a, b + 1)
bobit = tuple(s)

In [25]:
np.ravel(bobit)

array([1, 1, 1, 1, 2, 1, 1, 1])

In [8]:
main()

[2018-06-09 23:20:07,497] Making new env: MountainCar-v0


AttributeError: 'Box' object has no attribute 'dtype'

In [10]:
# Required for DQN
env.reset()
new_obs, rew, done, _ = env.step(1)
o = env.observation_space
a = env.action_space.n

In [14]:
print(new_obs,rew,done,_,o,a)

[ -5.88068441e-01   4.84075972e-04] -1.0 False {} Box(2,) 3


In [15]:
env.action_space

Discrete(3)