In [15]:
%matplotlib inline
%load_ext autoreload
%autoreload 2

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import json
from agents import Agent
from mouselab import MouselabEnv
from distributions import Normal, Categorical
from model_utils import read_bo_policy
from policies import FixedPlanPolicy, LiederPolicy, RandomTreePolicy
from evaluation import *
from pprint import pprint
import ast

In [7]:
def make_env(depth, reward, cost, ground_truth=False):
    """Returns a MouselabEnv with given depth and cost. 
    If `ground_truth` is True, the reward observed at a given node will be
    constant across runs on this env. This reduces variance of the return."""
    env = MouselabEnv(depth, reward=reward, cost=cost)
    if ground_truth:
        env.ground_truth = np.array([0, *reward.sample(len(env.tree) - 1)])
    return env

def make_envs(depth, reward, cost, n=100, ground_truth=None):
    # Note, ground_truth can be an int in which case it acts as a random seed.
    if ground_truth is not None:
        np.random.seed(ground_truth)
        return [make_env(depth, reward, cost, True) for _ in range(n)]
    else:
        return [make_env(depth, reward, cost, False)] * n

In [8]:
dist = Normal(0,10)
reward = dist.to_discrete(6)
costs = [0.1,1.25,4.00]
stimuli_envs ={str(cost):make_envs([4,1,2], reward, cost, n=16, ground_truth=1) for cost in costs}
stimuli_envs

{'0.1': [<mouselab.MouselabEnv at 0x7fe5e2c579b0>,
 '1.25': [<mouselab.MouselabEnv at 0x7fe5df7954e0>,
 '4.0': [<mouselab.MouselabEnv at 0x7fe5df728a58>,
  <mouselab.MouselabEnv at 0x7fe5df739c50>]}

In [9]:
optimal_reward = np.zeros((16,3))
worst_reward = np.zeros((16,3))
mean_reward = np.zeros((16,3))

lc_pol_reward = np.zeros((16,3))
clicks = np.zeros((16,3))

# samples2 = np.zeros((5000,16,3))

for cost_id in range(3):
    
    policy = read_bo_policy(costs[cost_id])
    envs =  stimuli_envs[str(costs[cost_id])]
    for env in envs:
        env.sample_term_reward = True
    ev = evaluate(policy, envs)
    
    lc_pol_reward[:,cost_id] = ev['util']
    clicks[:,cost_id] = ev['observations']
    
#     for i in range(5000):
#         random_policy = RandomTreePolicy()
#         samples2[i,:,cost_id] = evaluate(random_policy, envs)['util']
        
    for env_id in range(16):
        env = envs[env_id]
        optimal_reward[env_id,cost_id] = env.true_Q(0)
        worst_reward[env_id,cost_id] = env.worst_Q(0)
        mean_reward[env_id,cost_id] = env.mean_Q(0)

In [10]:
# rand_reward_samples2 = np.zeros((10000,16,3))
# for sample in range(10000):
#     for cost_id in range(3):
#         envs =  stimuli_envs[str(costs[cost_id])]
#         for env_id in range(16):
#             env = envs[env_id]
#             rand_reward_samples2[sample,env_id,cost_id] = env.rand_Q(0)

In [11]:
optimal_reward

array([[  4.,   4.,   4.],
       [ 36.,  36.,  36.],
       [ 36.,  36.,  36.],
       [ -4.,  -4.,  -4.],
       [ 28.,  28.,  28.],
       [ 28.,  28.,  28.],
       [ 28.,  28.,  28.],
       [ 28.,  28.,  28.],
       [ 20.,  20.,  20.],
       [ 12.,  12.,  12.],
       [ 28.,  28.,  28.],
       [ 12.,  12.,  12.],
       [ 36.,  36.,  36.],
       [ 44.,  44.,  44.],
       [ 28.,  28.,  28.],
       [ 36.,  36.,  36.]])

In [12]:
worst_reward

array([[-36., -36., -36.],
       [-12., -12., -12.],
       [-20., -20., -20.],
       [-36., -36., -36.],
       [-12., -12., -12.],
       [ -4.,  -4.,  -4.],
       [ -4.,  -4.,  -4.],
       [-60., -60., -60.],
       [-20., -20., -20.],
       [-36., -36., -36.],
       [-44., -44., -44.],
       [-20., -20., -20.],
       [-20., -20., -20.],
       [-36., -36., -36.],
       [-20., -20., -20.],
       [-12., -12., -12.]])

In [13]:
mean_reward

array([[-13., -13., -13.],
       [  5.,   5.,   5.],
       [ 12.,  12.,  12.],
       [-18., -18., -18.],
       [  2.,   2.,   2.],
       [ 10.,  10.,  10.],
       [  9.,   9.,   9.],
       [ -1.,  -1.,  -1.],
       [ -5.,  -5.,  -5.],
       [-11., -11., -11.],
       [ -5.,  -5.,  -5.],
       [ -2.,  -2.,  -2.],
       [  9.,   9.,   9.],
       [ -4.,  -4.,  -4.],
       [  9.,   9.,   9.],
       [ 10.,  10.,  10.]])

In [14]:
lc_pol_reward

array([[  2.6 ,  -9.75,  -4.  ],
       [ 35.5 ,  26.  ,  28.  ],
       [ 35.1 ,  24.25,  24.  ],
       [ -5.5 , -19.  , -12.  ],
       [ 27.3 ,  24.25,  20.  ],
       [ 27.  ,  10.  ,  16.  ],
       [ 27.  ,  16.75,  -8.  ],
       [ 26.7 ,  10.  ,   0.  ],
       [ 19.2 ,  13.75, -28.  ],
       [ 11.  ,   4.5 ,  -4.  ],
       [ 27.1 ,  18.  ,  -4.  ],
       [ 10.7 ,   0.75, -16.  ],
       [ 35.4 ,  16.25,  16.  ],
       [ 43.6 ,  40.25,  16.  ],
       [ 27.2 ,  18.  ,  20.  ],
       [ 34.8 ,  24.75,  -4.  ]])

In [15]:
lc_pol_reward - mean_reward

array([[ 15.6 ,   3.25,   9.  ],
       [ 30.5 ,  21.  ,  23.  ],
       [ 23.1 ,  12.25,  12.  ],
       [ 12.5 ,  -1.  ,   6.  ],
       [ 25.3 ,  22.25,  18.  ],
       [ 17.  ,   0.  ,   6.  ],
       [ 18.  ,   7.75, -17.  ],
       [ 27.7 ,  11.  ,   1.  ],
       [ 24.2 ,  18.75, -23.  ],
       [ 22.  ,  15.5 ,   7.  ],
       [ 32.1 ,  23.  ,   1.  ],
       [ 12.7 ,   2.75, -14.  ],
       [ 26.4 ,   7.25,   7.  ],
       [ 47.6 ,  44.25,  20.  ],
       [ 18.2 ,   9.  ,  11.  ],
       [ 24.8 ,  14.75, -14.  ]])

In [16]:
rel = (lc_pol_reward-mean_reward)/(lc_pol_reward-mean_reward)
rel

/home/sayan/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[  1.,   1.,   1.],
       [  1.,   1.,   1.],
       [  1.,   1.,   1.],
       [  1.,   1.,   1.],
       [  1.,   1.,   1.],
       [  1.,  nan,   1.],
       [  1.,   1.,   1.],
       [  1.,   1.,   1.],
       [  1.,   1.,   1.],
       [  1.,   1.,   1.],
       [  1.,   1.,   1.],
       [  1.,   1.,   1.],
       [  1.,   1.,   1.],
       [  1.,   1.,   1.],
       [  1.,   1.,   1.],
       [  1.,   1.,   1.]])

In [17]:
clicks

array([[ 14.,  11.,   2.],
       [  5.,   8.,   2.],
       [  9.,   3.,   1.],
       [ 15.,  12.,   2.],
       [  7.,   3.,   2.],
       [ 10.,   8.,   1.],
       [ 10.,   9.,   1.],
       [ 13.,   8.,   1.],
       [  8.,   5.,   2.],
       [ 10.,   6.,   2.],
       [  9.,   8.,   2.],
       [ 13.,   9.,   1.],
       [  6.,   3.,   1.],
       [  4.,   3.,   1.],
       [  8.,   8.,   2.],
       [ 12.,   9.,   2.]])

In [18]:
np.mean(clicks[:,2])

1.5625

In [19]:
np.savetxt('../experiments/data/stimuli/exp1/optimal1A.3.csv', lc_pol_reward, delimiter=",")
np.savetxt('../experiments/data/stimuli/exp1/score_pi_star1A.3.csv', lc_pol_reward, delimiter=",")
np.savetxt('../experiments/data/stimuli/exp1/worst1A.3.csv', mean_reward, delimiter=",")
np.savetxt('../experiments/data/stimuli/exp1/rel_score_pi_star1A.3.csv', rel, delimiter=",")
np.savetxt('../experiments/data/stimuli/exp1/nr_observations_pi_star1A.3.csv', clicks, delimiter=",")

# Pilot PRs

In [29]:
costs = [0.10,1.25,4.00] 
stimuli_envs ={str(cost):make_envs([4,1,2], reward, cost, n=16, ground_truth=1) for cost in costs}
stimuli_envs

{'0.1': [<mouselab.MouselabEnv at 0x7fe5d3e47ba8>,
 '1.25': [<mouselab.MouselabEnv at 0x7fe5d3efada0>,
 '4.0': [<mouselab.MouselabEnv at 0x7fe5d3e5f4a8>,
  <mouselab.MouselabEnv at 0x7fe5d3e6c668>]}

In [30]:
trials = pd.read_csv('../experiments/data/human/1.8/trials.csv')
trials = trials.loc[trials['info_cost'].isin(costs)]
trials

Unnamed: 0  pid  info_cost PR_type message  trial_index  trial_id  \
0              0    0       1.25    none    none            1    8969.0   
1              1    0       1.25    none    none            2    9359.0   
2              2    0       1.25    none    none            3    9876.0   
3              3    0       1.25    none    none            4    6615.0   
4              4    0       1.25    none    none            5    5157.0   
5              5    0       1.25    none    none            6    7410.0   
6              6    0       1.25    none    none            7    6264.0   
7              7    0       1.25    none    none            8    7618.0   
8              8    0       1.25    none    none            9    8818.0   
9              9    0       1.25    none    none           10    7003.0   
10            10    0       1.25    none    none           11    6060.0   
11            11    0       1.25    none    none           12    6426.0   
12            12    0       1.25    none    none           13    6337.0   
13            13    0       1.25    none    none           14    7370.0   
14            14    0       1.25    none    none           15    5033.0   
15            15    0       1.25    none    none           16    5638.0   
16            16    1       4.00    none    none            1   13397.0   
17            17    1       4.00    none    none            2   12579.0   
18            18    1       4.00    none    none            3   14313.0   
19            19    1       4.00    none    none            4   12675.0   
20            20    1       4.00    none    none            5   10323.0   
21            21    1       4.00    none    none            6   12086.0   
22            22    1       4.00    none    none            7   12291.0   
23            23    1       4.00    none    none            8   14785.0   
24            24    1       4.00    none    none            9   12615.0   
25            25    1       4.00    none    none           10   13051.0   
26            26    1       4.00    none    none           11   12022.0   
27            27    1       4.00    none    none           12   11337.0   
28            28    1       4.00    none    none           13   12997.0   
29            29    1       4.00    none    none           14   12186.0   
...          ...  ...        ...     ...     ...          ...       ...   
1410        1472  101       0.10    none    none            3    2306.0   
1411        1473  101       0.10    none    none            4    4860.0   
1412        1474  101       0.10    none    none            5    3376.0   
1413        1475  101       0.10    none    none            6    4684.0   
1414        1476  101       0.10    none    none            7     163.0   
1415        1477  101       0.10    none    none            8    3335.0   
1416        1478  101       0.10    none    none            9      54.0   
1417        1479  101       0.10    none    none           10    1269.0   
1418        1480  101       0.10    none    none           11    2319.0   
1419        1481  101       0.10    none    none           12    4439.0   
1420        1482  101       0.10    none    none           13    3324.0   
1421        1483  101       0.10    none    none           14    1597.0   
1422        1484  101       0.10    none    none           15    3845.0   
1423        1485  101       0.10    none    none           16    1313.0   
1424        1486  102       1.25    none    none            1    7618.0   
1425        1487  102       1.25    none    none            2    5157.0   
1426        1488  102       1.25    none    none            3    8818.0   
1427        1489  102       1.25    none    none            4    7410.0   
1428        1490  102       1.25    none    none            5    6615.0   
1429        1491  102       1.25    none    none            6    9359.0   
1430        1492  102       1.25    none    none            7    6264.0   
1431        1493  102       1.2

In [31]:
trials['pr_sum'] = np.zeros(trials.shape[0])
trials['click_prs'] = [[]]*trials.shape[0]

In [32]:
with open('../experiments/exp1/static/json/q_weights.json') as data_file:    
    q_weights = json.load(data_file)
pprint(q_weights)

{'0.10': [2.053410166049148,
          0.035432105933805545,
          0.027055750247385255,
          0.9432457551263028,
          0.9979765410879625],
 '1.25': [1.7132112787775398,
          0.46426212124574967,
          0.23605538377611573,
          0.4252363266867176,
          0.993457670362997],
 '4.00': [1.0204049741183023,
          0.9892671828885087,
          -0.013161214101093,
          0.01785957275841159,
          1.0004646109245603]}


In [ ]:
for index, row in trials.iterrows():
    if index % 20 == 0: print(index)
    cost = row['info_cost']
    s_cost = str(cost)
    trial_id = row['trial_index']
    
#     stimuli_envs = make_envs([4,1,2], reward, cost, n=16, ground_truth=1)
#     menv = stimuli_envs[trial_id-1]
    menv = stimuli_envs[s_cost][trial_id-1]
       
    if s_cost == '0.1': s_cost = '0.10'
    elif s_cost == '4.0': s_cost = '4.00'
    q_weight = q_weights[s_cost]
    
    clicks = ast.literal_eval(row['clicks'])
    clicks.append(17)
    pr_sum = 0
    click_prs = []
    for a in clicks:
        f = menv.action_features(a)
        pr = np.inner(q_weight,f) - np.max([np.inner(q_weight,menv.action_features(a2)) for a2 in menv.actions(menv._state)])
        menv.step(a)
        pr_sum += pr
        click_prs.append(pr)
    trials.set_value(index,'pr_sum',pr_sum)
    trials.set_value(index,'click_prs',click_prs)
    menv.reset()

0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
520
540
560


In [ ]:
csv_ready = trials[['pid','info_cost','trial_index','pr_sum','click_prs']]

In [42]:
csv_ready

pid  info_cost  trial_index     pr_sum  \
0       0       0.10            1 -19.473024   
1       0       0.10            2 -14.298082   
2       0       0.10            3  -1.158616   
3       0       0.10            4 -12.732936   
4       0       0.10            5  -7.742030   
5       0       0.10            6 -12.339585   
6       0       0.10            7 -14.684785   
7       0       0.10            8  -2.808495   
8       0       0.10            9  -0.836415   
9       0       0.10           10 -16.712976   
10      0       0.10           11  -1.379754   
11      0       0.10           12  -7.230512   
12      0       0.10           13  -9.580977   
13      0       0.10           14 -10.826030   
14      0       0.10           15  -0.275379   
15      0       0.10           16  -0.686149   
32      2       1.25            1  -9.251955   
33      2       1.25            2  -3.450877   
34      2       1.25            3  -9.761835   
35      2       1.25            4 -13.622359   
36      2       1.25            5 -10.039142   
37      2       1.25            6  -0.877168   
38      2       1.25            7  -6.453665   
39      2       1.25            8  -1.439432   
40      2       1.25            9  -3.750411   
41      2       1.25           10  -7.592888   
42      2       1.25           11  -6.856786   
43      2       1.25           12 -10.080156   
44      2       1.25           13  -1.145928   
45      2       1.25           14 -19.845851   
...   ...        ...          ...        ...   
1970  135       1.25            3   0.000000   
1971  135       1.25            4  -7.014958   
1972  135       1.25            5 -10.944829   
1973  135       1.25            6 -10.944829   
1974  135       1.25            7 -10.944829   
1975  135       1.25            8 -10.944829   
1976  135       1.25            9  -8.078977   
1977  135       1.25           10  -8.332457   
1978  135       1.25           11  -9.586120   
1979  135       1.25           12  -9.586120   
1980  135       1.25           13 -10.944829   
1981  135       1.25           14 -13.434546   
1982  135       1.25           15 -10.944829   
1983  135       1.25           16 -10.076759   
1984  137       0.10            1 -20.808384   
1985  137       0.10            2 -20.808384   
1986  137       0.10            3 -20.808384   
1987  137       0.10            4 -20.808384   
1988  137       0.10            5 -14.851678   
1989  137       0.10            6 -17.715089   
1990  137       0.10            7 -12.372749   
1991  137       0.10            8 -11.044001   
1992  137       0.10            9 -15.006348   
1993  137       0.10           10 -18.206022   
1994  137       0.10           11 -17.080801   
1995  137       0.10           12 -19.350584   
1996  137       0.10           13 -16.360370   
1997  137       0.10           14 -12.372749   
1998  137       0.10           15 -11.522703   
1999  137       0.10           16 -17.080801   

                                              click_prs  
0                [0.0, -0.324304015787, -19.1487199638]  
1     [0.0, -0.210504570876, -0.382266880015, -0.382...  
2      [0.0, -0.131482925701, 0.0, 0.0, -1.02713289086]  
3     [0.0, -0.024981893567, -0.213568828633, -0.448...  
4     [0.0, 0.0, 0.0, -0.103683559651, -0.3740098722...  
5           [0.0, 0.0, -0.142487954368, -12.1970973059]  
6     [0.0, -0.0187194016522, -0.335429268645, -0.33...  
7     [0.0, 0.0, -0.210504570876, -0.232311392331, -...  
8     [0.0, -0.210504570876, -0.210504570876, -0.232...  
9     [0.0, 0.0, -0.593528882527, -0.632584865513, -...  
10    [0.0, 0.0, -0.0473923034189, -0.0473923034189,...  
11    [0.0, -0.324304015787, -0.183853183511, 0.0, 0...  
12    [0.0, -0.312460410046, -0.317369298392, -0.387...  
13    [0.0, -0.610566057277, -0.610566057277, -0.513...  
14    [0.0, 0.0, -0.0915496279141, 0.0, 0.0, 0.0, -0...  
15    [0.0, -0.0187194016522, 0.0, -0.106775719211, ...  
32                           [0.0, 0.0, -9.

In [43]:
res = trials.set_index(['pid','info_cost','trial_index'])['click_prs'].apply(pd.Series).stack()
res = res.reset_index()
res.columns = ['pid','info_cost','trial_index','click_num','click_pr']
res

pid  info_cost  trial_index  click_num   click_pr
0       0        0.1            1          0   0.000000
1       0        0.1            1          1  -0.324304
2       0        0.1            1          2 -19.148720
3       0        0.1            2          0   0.000000
4       0        0.1            2          1  -0.210505
5       0        0.1            2          2  -0.382267
6       0        0.1            2          3  -0.382267
7       0        0.1            2          4  -0.516120
8       0        0.1            2          5  -0.521028
9       0        0.1            2          6 -12.285895
10      0        0.1            3          0   0.000000
11      0        0.1            3          1  -0.131483
12      0        0.1            3          2   0.000000
13      0        0.1            3          3   0.000000
14      0        0.1            3          4  -1.027133
15      0        0.1            4          0   0.000000
16      0        0.1            4          1  -0.024982
17      0        0.1            4          2  -0.213569
18      0        0.1            4          3  -0.448732
19      0        0.1            4          4  -0.024982
20      0        0.1            4          5  -0.375666
21      0        0.1            4          6  -0.448732
22      0        0.1            4          7 -11.196274
23      0        0.1            5          0   0.000000
24      0        0.1            5          1   0.000000
25      0        0.1            5          2   0.000000
26      0        0.1            5          3  -0.103684
27      0        0.1            5          4  -0.374010
28      0        0.1            5          5  -0.362519
29      0        0.1            5          6  -6.901817
...   ...        ...          ...        ...        ...
6148  137        0.1            5          1  -0.210505
6149  137        0.1            5          2 -14.641173
6150  137        0.1            6          0   0.000000
6151  137        0.1            6          1   0.000000
6152  137        0.1            6          2 -17.715089
6153  137        0.1            7          0   0.000000
6154  137        0.1            7          1 -12.372749
6155  137        0.1            8          0   0.000000
6156  137        0.1            8          1   0.000000
6157  137        0.1            8          2  -0.210505
6158  137        0.1            8          3 -10.833496
6159  137        0.1            9          0   0.000000
6160  137        0.1            9          1  -0.024982
6161  137        0.1            9          2 -14.981366
6162  137        0.1           10          0   0.000000
6163  137        0.1           10          1 -18.206022
6164  137        0.1           11          0   0.000000
6165  137        0.1           11          1 -17.080801
6166  137        0.1           12          0   0.000000
6167  137        0.1           12          1 -19.350584
6168  137        0.1           13          0   0.000000
6169  137        0.1           13          1   0.000000
6170  137        0.1           13          2 -16.360370
6171  137        0.1           14          0   0.000000
6172  137        0.1           14          1 -12.372749
6173  137        0.1           15          0   0.000000
6174  137        0.1           15          1  -0.210505
6175  137        0.1           15          2 -11.312199
6176  137        0.1           16          0   0.000000
6177  137        0.1           16          1 -17.080801

[6178 rows x 5 columns]

In [44]:
csv_ready.to_csv('../experiments/data/human/0.995/pilot_prs.csv')
res.to_csv('../experiments/data/human/0.995/pilot_click_prs.csv')

# Object-Level PRs

In [9]:
import json
with open('../backward_planning/experiment1/experiment/static/json/mcrl_trials/increasing.json') as data_file:    
    data = json.load(data_file)

In [60]:
data[0]

{'qs': {'0 _ _ _ _ _ _ _ _ _ _ _ _': {'1': 39.45,
   '10': 39.95,
   '11': 39.97,
   '12': 39.97,
   '13': 0.0,
   '2': 39.95,
   '3': 39.97,
   '4': 39.97,
   '5': 39.45,
   '6': 39.95,
   '7': 39.97,
   '8': 39.97,
   '9': 39.45},
  '0 _ _ _ _ _ _ _ _ _ _ _ -24': {'1': 37.52,
   '10': 37.7,
   '11': 38.09,
   '13': 0.0,
   '2': 37.96,
   '3': 38.09,
   '4': 38.09,
   '5': 37.52,
   '6': 37.96,
   '7': 38.09,
   '8': 38.09,
   '9': 37.39},
  '0 _ _ _ _ _ _ _ _ _ _ -48 _': {'1': 37.47,
   '10': 37.64,
   '12': 38.05,
   '13': 0.0,
   '2': 37.92,
   '3': 38.05,
   '4': 38.05,
   '5': 37.47,
   '6': 37.92,
   '7': 38.05,
   '8': 38.05,
   '9': 37.34},
  '0 _ _ _ _ _ _ _ _ _ _ -48 -24': {'1': 34.37,
   '10': 34.09,
   '13': 0.0,
   '2': 34.75,
   '3': 35.03,
   '4': 35.03,
   '5': 34.37,
   '6': 34.75,
   '7': 35.03,
   '8': 35.03,
   '9': 34.06},
  '0 _ _ _ _ _ _ _ _ _ -4 _ _': {'1': 38.52,
   '11': 38.65,
   '12': 38.65,
   '13': 0.0,
   '2': 38.96,
   '3': 39.19,
   '4': 39.19,
   '5':

In [61]:
dcts = []
inacts = [1,5,9]
directs = ["up","right","left"]
for i in data: 
#     print(i['stateRewards'])
    env = MouselabEnv.new_symmetric([3,1,2], None, ground_truth=i['stateRewards'], cost=0.01)
    
    qs0 = env.true_Q(0)
    
    dct = {}
    prs = [env.true_Q(inacts[i])-qs0 for i in range(3)]
    dct['opt_act'] = directs[np.argmax(prs)]
    dct['prs']={directs[i]: prs[i] for i in range(3)}
    dct['trial_id'] = i['trial_id']
    dcts.append(dct)

In [57]:
olprs

[[0.0, -66.0, -62.0],
 [0.0, -46.0, -44.0],
 [-68.0, 0.0, -66.0],
 [-48.0, -60.0, 0.0],
 [-84.0, -60.0, 0.0],
 [0.0, -80.0, -6.0],
 [-26.0, -108.0, 0.0],
 [-26.0, -20.0, 0.0],
 [-26.0, 0.0, -64.0],
 [-48.0, 0.0, -66.0],
 [-26.0, 0.0, -14.0],
 [-38.0, -38.0, 0.0],
 [-10.0, -74.0, 0.0],
 [-102.0, -18.0, 0.0],
 [-4.0, -38.0, 0.0],
 [0.0, -98.0, -38.0],
 [0.0, -18.0, -44.0],
 [-6.0, 0.0, -64.0],
 [-94.0, 0.0, -56.0],
 [-6.0, -44.0, 0.0],
 [-72.0, -42.0, 0.0],
 [0.0, -2.0, -32.0],
 [0.0, 0.0, -30.0],
 [-32.0, 0.0, -6.0],
 [0.0, -102.0, -8.0],
 [-34.0, 0.0, -28.0],
 [-106.0, -36.0, 0.0],
 [-6.0, 0.0, -16.0],
 [-24.0, -14.0, 0.0],
 [-90.0, -14.0, 0.0],
 [0.0, -78.0, -38.0],
 [-28.0, -10.0, 0.0],
 [-4.0, 0.0, -80.0],
 [-64.0, -12.0, 0.0],
 [0.0, -32.0, -88.0],
 [0.0, -24.0, -36.0],
 [-14.0, 0.0, -8.0],
 [0.0, -72.0, -14.0],
 [-72.0, 0.0, -8.0],
 [-22.0, 0.0, -34.0],
 [-66.0, -92.0, 0.0],
 [-12.0, 0.0, -6.0],
 [0.0, -22.0, -30.0],
 [-116.0, -16.0, 0.0],
 [-18.0, -90.0, 0.0],
 [-20.0, -62.0, 0.0