In [11]:
%matplotlib inline
%load_ext autoreload
%autoreload 2

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import json
from agents import Agent
from mouselab import MouselabEnv
from distributions import Normal, Categorical
from policies import FixedPlanPolicy, LiederPolicy
from evaluation import *
from pprint import pprint
import ast

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [2]:
trials = pd.read_csv('../experiments/data/human/0.991/trials.csv')

In [3]:
trials

Unnamed: 0  pid  info_cost PR_type message  trial_index  trial_i  \
0              0    0       1.00    none    none            1      NaN   
1              1    0       1.00    none    none            2      NaN   
2              2    0       1.00    none    none            3      NaN   
3              3    0       1.00    none    none            4      NaN   
4              4    0       1.00    none    none            5      NaN   
5              5    0       1.00    none    none            6      NaN   
6              6    0       1.00    none    none            7      NaN   
7              7    0       1.00    none    none            8      NaN   
8              8    0       1.00    none    none            9      NaN   
9              9    0       1.00    none    none           10      NaN   
10            10    0       1.00    none    none           11      NaN   
11            11    0       1.00    none    none           12      NaN   
12            12    0       1.00    none    none           13      NaN   
13            13    0       1.00    none    none           14      NaN   
14            14    0       1.00    none    none           15      NaN   
15            15    0       1.00    none    none           16      NaN   
16            16    1       0.25    none    none            1      NaN   
17            17    1       0.25    none    none            2      NaN   
18            18    1       0.25    none    none            3      NaN   
19            19    1       0.25    none    none            4      NaN   
20            20    1       0.25    none    none            5      NaN   
21            21    1       0.25    none    none            6      NaN   
22            22    1       0.25    none    none            7      NaN   
23            23    1       0.25    none    none            8      NaN   
24            24    1       0.25    none    none            9      NaN   
25            25    1       0.25    none    none           10      NaN   
26            26    1       0.25    none    none           11      NaN   
27            27    1       0.25    none    none           12      NaN   
28            28    1       0.25    none    none           13      NaN   
29            29    1       0.25    none    none           14      NaN   
...          ...  ...        ...     ...     ...          ...      ...   
1506        1547  104       4.00    none    none            3      NaN   
1507        1548  104       4.00    none    none            4      NaN   
1508        1549  104       4.00    none    none            5      NaN   
1509        1550  104       4.00    none    none            6      NaN   
1510        1551  104       4.00    none    none            7      NaN   
1511        1552  104       4.00    none    none            8      NaN   
1512        1553  104       4.00    none    none            9      NaN   
1513        1554  104       4.00    none    none           10      NaN   
1514        1555  104       4.00    none    none           11      NaN   
1515        1556  104       4.00    none    none           12      NaN   
1516        1557  104       4.00    none    none           13      NaN   
1517        1558  104       4.00    none    none           14      NaN   
1518        1559  104       4.00    none    none           15      NaN   
1519        1560  104       4.00    none    none           16      NaN   
1520        1561  105       1.00    none    none            1      NaN   
1521        1562  105       1.00    none    none            2      NaN   
1522        1563  105       1.00    none    none            3      NaN   
1523        1564  105       1.00    none    none            4      NaN   
1524        1565  105       1.00    none    none            5      NaN   
1525        1566  105       1.00    none    none            6      NaN   
1526        1567  105       1.00    none    none            7      NaN   
1527        1568  105       1.00    none    none            8      NaN   
1528      

In [4]:
def make_env(depth, reward, cost, ground_truth=False):
    """Returns a MouselabEnv with given depth and cost. 
    If `ground_truth` is True, the reward observed at a given node will be
    constant across runs on this env. This reduces variance of the return."""
    env = MouselabEnv(depth, reward=reward, cost=cost)
    if ground_truth:
        env.ground_truth = np.array([0, *reward.sample(len(env.tree) - 1)])
    return env

def make_envs(depth, reward, cost, n=100, ground_truth=None):
    # Note, ground_truth can be an int in which case it acts as a random seed.
    if ground_truth is not None:
        np.random.seed(ground_truth)
        return [make_env(depth, reward, cost, True) for _ in range(n)]
    else:
        return [make_env(depth, reward, cost, False)] * n

In [5]:
with open('../experiments/exp1/static/json/q_weights.json') as data_file:    
    q_weights = json.load(data_file)
pprint(q_weights)

{'0.25': [2.3252393134113225,
          0.09975155227317743,
          0.08032182729437333,
          0.8450937421220647,
          0.997435322775085],
 '1.00': [1.9484115264310722,
          0.4288647055137153,
          0.269370854918958,
          0.44258532182537325,
          0.9912367388407017],
 '4.00': [1.02455453397985,
          0.9723698649146737,
          0.0048616156760657794,
          0.01790135732732076,
          1.000241178138463]}


In [14]:
trials['pr_sum'] = np.zeros(trials.shape[0])
trials['click_prs'] = [[]]*trials.shape[0]

In [68]:
dist = Normal(0,10)
reward = dist.to_discrete(6)
costs = [0.25,1.00,4.00]
stimuli_envs ={str(cost):make_envs([4,1,2], reward, cost, n=16, ground_truth=1) for cost in costs}
stimuli_envs

{'0.25': [<mouselab.MouselabEnv at 0x2aacda66b710>,
 '1.0': [<mouselab.MouselabEnv at 0x2aacda6c2e10>,
 '4.0': [<mouselab.MouselabEnv at 0x2aacda6d33c8>,
  <mouselab.MouselabEnv at 0x2aacda6df390>]}

In [69]:
thetas = [[2.55,0.47,0.18,0.35,1.0],[1.00,0.42,0.42,0.17,1.0],[5.74,0.32,0.00,0.68,1.0]]
optimal_reward = np.zeros((16,3))
worst_reward = np.zeros((16,3))
lc_pol_reward = np.zeros((16,3))
clicks = np.zeros((16,3))
for cost_id in range(3):
    policy = LiederPolicy(thetas[cost_id])
    envs =  stimuli_envs[str(costs[cost_id])]
    ev = evaluate(policy, envs)
    lc_pol_reward[:,cost_id] = ev['util']
    clicks[:,cost_id] = ev['observations']
    for env_id in range(16):
        env.reset()
        env = envs[env_id]
        optimal_reward[env_id,cost_id] = env.true_Q(0)
        worst_reward[env_id,cost_id] = env.worst_Q(0)
        env.reset()

In [71]:
optimal_reward

array([[  4.,   4.,   4.],
       [ 36.,  36.,  36.],
       [ 36.,  36.,  36.],
       [ -4.,  -4.,  -4.],
       [ 28.,  28.,  28.],
       [ 28.,  28.,  28.],
       [ 28.,  28.,  28.],
       [ 28.,  28.,  28.],
       [ 20.,  20.,  20.],
       [ 12.,  12.,  12.],
       [ 28.,  28.,  28.],
       [ 12.,  12.,  12.],
       [ 36.,  36.,  36.],
       [ 44.,  44.,  44.],
       [ 28.,  28.,  28.],
       [ 36.,  36.,  36.]])

In [72]:
worst_reward

array([[-36., -36., -36.],
       [-12., -12., -12.],
       [-20., -20., -20.],
       [-36., -36., -36.],
       [-12., -12., -12.],
       [ -4.,  -4.,  -4.],
       [ -4.,  -4.,  -4.],
       [-60., -60., -60.],
       [-20., -20., -20.],
       [-36., -36., -36.],
       [-44., -44., -44.],
       [-20., -20., -20.],
       [-20., -20., -20.],
       [-36., -36., -36.],
       [-20., -20., -20.],
       [-12., -12., -12.]])

In [73]:
lc_pol_reward

array([[  1.000e+00,  -8.000e+00,  -4.441e-16],
       [  3.400e+01,   2.800e+01,  -4.441e-16],
       [  3.375e+01,   2.700e+01,  -4.441e-16],
       [  5.750e+00,   1.000e+00,  -4.441e-16],
       [  2.575e+01,   2.000e+01,  -4.441e-16],
       [  2.575e+01,   1.100e+01,  -4.441e-16],
       [  2.575e+01,   1.900e+01,  -4.441e-16],
       [  2.475e+01,   1.100e+01,  -4.441e-16],
       [  1.750e+01,   1.300e+01,  -4.441e-16],
       [  9.250e+00,   1.000e+00,  -4.441e-16],
       [  2.600e+01,   2.000e+01,  -4.441e-16],
       [  8.750e+00,   2.000e+00,  -4.441e-16],
       [  3.400e+01,   2.700e+01,  -4.441e-16],
       [  3.100e+01,   2.900e+01,  -4.441e-16],
       [  2.625e+01,   1.800e+01,  -4.441e-16],
       [  3.350e+01,   7.000e+00,  -4.441e-16]])

In [74]:
rel = (lc_pol_reward-worst_reward)/(optimal_reward-worst_reward)
rel

array([[ 0.925,  0.7  ,  0.9  ],
       [ 0.958,  0.833,  0.25 ],
       [ 0.96 ,  0.839,  0.357],
       [ 1.305,  1.156,  1.125],
       [ 0.944,  0.8  ,  0.3  ],
       [ 0.93 ,  0.469,  0.125],
       [ 0.93 ,  0.719,  0.125],
       [ 0.963,  0.807,  0.682],
       [ 0.938,  0.825,  0.5  ],
       [ 0.943,  0.771,  0.75 ],
       [ 0.972,  0.889,  0.611],
       [ 0.898,  0.688,  0.625],
       [ 0.964,  0.839,  0.357],
       [ 0.838,  0.812,  0.45 ],
       [ 0.964,  0.792,  0.417],
       [ 0.948,  0.396,  0.25 ]])

In [75]:
clicks

array([[ 12.,  12.,   0.],
       [  8.,   8.,   0.],
       [  9.,   9.,   0.],
       [  9.,   7.,   0.],
       [  9.,   4.,   0.],
       [  9.,   9.,   0.],
       [  9.,   9.,   0.],
       [ 13.,   9.,   0.],
       [ 10.,   7.,   0.],
       [ 11.,  11.,   0.],
       [  8.,   8.,   0.],
       [ 13.,  10.,   0.],
       [  8.,   5.,   0.],
       [  4.,   3.,   0.],
       [  7.,  10.,   0.],
       [ 10.,   9.,   0.]])

In [77]:
np.savetxt('../experiments/data/stimuli/exp1/optimal1A.2.csv', optimal_reward, delimiter=",")
np.savetxt('../experiments/data/stimuli/exp1/worst1A.2.csv', worst_reward, delimiter=",")
np.savetxt('../experiments/data/stimuli/exp1/rel_score_pi_star1A.2.csv', rel, delimiter=",")
np.savetxt('../experiments/data/stimuli/exp1/nr_observations_pi_star1A.2.csv', clicks, delimiter=",")

In [13]:
for index, row in trials.iterrows():
    if index % 20 == 0: print(index)
    cost = row['info_cost']
    s_cost = str(cost)
    trial_id = row['trial_index']
    
#     stimuli_envs = make_envs([4,1,2], reward, cost, n=16, ground_truth=1)
#     menv = stimuli_envs[trial_id-1]
    menv = stimuli_envs[s_cost][trial_id-1]
       
    if s_cost == '1.0': s_cost = '1.00'
    elif s_cost == '4.0': s_cost = '4.00'
    q_weight = q_weights[s_cost]
    
    clicks = ast.literal_eval(row['clicks'])
    clicks.append(17)
    pr_sum = 0
    click_prs = []
    for a in clicks:
        f = menv.action_features(a)
        pr = np.inner(q_weight,f) - np.max([np.inner(q_weight,menv.action_features(a2)) for a2 in menv.actions(menv._state)])
        menv.step(a)
        pr_sum += pr
        click_prs.append(pr)
    trials.set_value(index,'pr_sum',pr_sum)
    trials.set_value(index,'click_prs',click_prs)
    menv.reset()

0
20


KeyboardInterrupt: 

In [48]:
csv_ready = trials[['pid','info_cost','trial_index','pr_sum','click_prs']]

In [49]:
csv_ready

pid  info_cost  trial_index     pr_sum  \
0       0       1.00            1 -21.801828   
1       0       1.00            2 -10.724908   
2       0       1.00            3  -5.819986   
3       0       1.00            4  -6.452739   
4       0       1.00            5  -6.910454   
5       0       1.00            6 -12.222219   
6       0       1.00            7 -12.222219   
7       0       1.00            8 -12.222219   
8       0       1.00            9 -12.222219   
9       0       1.00           10 -10.693319   
10      0       1.00           11  -8.530718   
11      0       1.00           12 -11.531289   
12      0       1.00           13 -12.222219   
13      0       1.00           14 -12.222219   
14      0       1.00           15  -9.196463   
15      0       1.00           16 -12.423147   
16      1       0.25            1 -19.290150   
17      1       0.25            2 -11.445353   
18      1       0.25            3  -8.413949   
19      1       0.25            4 -11.552673   
20      1       0.25            5 -11.445353   
21      1       0.25            6 -11.568436   
22      1       0.25            7 -14.079975   
23      1       0.25            8 -11.445353   
24      1       0.25            9 -12.958081   
25      1       0.25           10 -13.685294   
26      1       0.25           11 -15.264744   
27      1       0.25           12 -10.914707   
28      1       0.25           13 -19.290150   
29      1       0.25           14 -17.234043   
...   ...        ...          ...        ...   
1506  104       4.00            3  -0.363699   
1507  104       4.00            4  -0.363699   
1508  104       4.00            5  -0.363699   
1509  104       4.00            6  -0.363699   
1510  104       4.00            7  -0.363699   
1511  104       4.00            8  -0.363699   
1512  104       4.00            9  -0.363699   
1513  104       4.00           10  -0.363699   
1514  104       4.00           11  -0.363699   
1515  104       4.00           12  -0.363699   
1516  104       4.00           13  -0.363699   
1517  104       4.00           14  -0.363699   
1518  104       4.00           15  -0.363699   
1519  104       4.00           16  -0.363699   
1520  105       1.00            1 -14.433363   
1521  105       1.00            2 -10.724908   
1522  105       1.00            3  -2.714158   
1523  105       1.00            4 -13.400003   
1524  105       1.00            5 -28.300925   
1525  105       1.00            6  -8.919758   
1526  105       1.00            7 -25.485823   
1527  105       1.00            8  -4.712430   
1528  105       1.00            9 -12.990829   
1529  105       1.00           10 -14.668846   
1530  105       1.00           11  -0.394992   
1531  105       1.00           12 -11.531289   
1532  105       1.00           13  -9.749815   
1533  105       1.00           14  -5.796933   
1534  105       1.00           15 -15.355129   
1535  105       1.00           16 -10.884975   

                                              click_prs  
0     [0.0, -3.48967110132, -4.38808088052, -4.38808...  
1                  [0.0, -1.78773376916, -8.9371740738]  
2                [0.0, -0.394992325395, -5.42499349295]  
3      [0.0, 0.0, 0.0, -0.432655729455, -6.02008290493]  
4                                 [0.0, -6.91045391442]  
5                                      [-12.2222185374]  
6                                      [-12.2222185374]  
7                                      [-12.2222185374]  
8                                      [-12.2222185374]  
9     [0.0, -0.432655729455, -1.1453229211, -1.14532...  
10    [0.0, -0.394992325395, 0.0, -1.25301416697, -1...  
11                                [0.0, -11.5312894479]  
12                                     [-12.2222185374]  
13                                     [-12.2222185374]  
14                    [-0.380648314282, -8.81581484015]  
15    [-0.380648314282, -0.740810834193, -11.3016880...  
16                                     [-19

In [39]:
res = trials.set_index(['pid','info_cost','trial_index'])['click_prs'].apply(pd.Series).stack()
res = res.reset_index()
res.columns = ['pid','info_cost','trial_index','click_num','click_pr']
res

pid  info_cost  trial_index  click_num   click_pr
0       0        1.0            1          0   0.000000
1       0        1.0            1          1  -3.489671
2       0        1.0            1          2  -4.388081
3       0        1.0            1          3  -4.388081
4       0        1.0            1          4   0.000000
5       0        1.0            1          5  -1.839783
6       0        1.0            1          6  -1.502107
7       0        1.0            1          7  -1.360207
8       0        1.0            1          8   0.000000
9       0        1.0            1          9  -1.253846
10      0        1.0            1         10  -1.360207
11      0        1.0            1         11  -1.360207
12      0        1.0            1         12   0.000000
13      0        1.0            1         13  -0.859637
14      0        1.0            1         14   0.000000
15      0        1.0            1         15   0.000000
16      0        1.0            1         16   0.000000
17      0        1.0            2          0   0.000000
18      0        1.0            2          1  -1.787734
19      0        1.0            2          2  -8.937174
20      0        1.0            3          0   0.000000
21      0        1.0            3          1  -0.394992
22      0        1.0            3          2  -5.424993
23      0        1.0            4          0   0.000000
24      0        1.0            4          1   0.000000
25      0        1.0            4          2   0.000000
26      0        1.0            4          3  -0.432656
27      0        1.0            4          4  -6.020083
28      0        1.0            5          0   0.000000
29      0        1.0            5          1  -6.910454
...   ...        ...          ...        ...        ...
8576  105        1.0           10          2   0.000000
8577  105        1.0           10          3  -2.976262
8578  105        1.0           10          4  -2.976262
8579  105        1.0           10          5  -8.283665
8580  105        1.0           11          0   0.000000
8581  105        1.0           11          1   0.000000
8582  105        1.0           11          2  -0.394992
8583  105        1.0           11          3   0.000000
8584  105        1.0           11          4   0.000000
8585  105        1.0           12          0   0.000000
8586  105        1.0           12          1 -11.531289
8587  105        1.0           13          0   0.000000
8588  105        1.0           13          1  -2.462813
8589  105        1.0           13          2  -2.492335
8590  105        1.0           13          3  -4.794667
8591  105        1.0           14          0   0.000000
8592  105        1.0           14          1   0.000000
8593  105        1.0           14          2   0.000000
8594  105        1.0           14          3  -1.787734
8595  105        1.0           14          4  -4.009199
8596  105        1.0           15          0   0.000000
8597  105        1.0           15          1  -1.787734
8598  105        1.0           15          2  -2.820734
8599  105        1.0           15          3  -2.820734
8600  105        1.0           15          4  -7.925928
8601  105        1.0           16          0   0.000000
8602  105        1.0           16          1  -0.432656
8603  105        1.0           16          2  -0.432656
8604  105        1.0           16          3  -1.145323
8605  105        1.0           16          4  -8.874340

[8606 rows x 5 columns]

In [50]:
csv_ready.to_csv('../experiments/data/human/0.991/pilot_prs.csv')
res.to_csv('../experiments/data/human/0.991/pilot_click_prs.csv')